/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'
import { imageEmits } from "element-plus"

export {}

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ElButton: typeof import("element-plus/es")["ElButton"]
    ElCard: typeof import("element-plus/es")["ElCard"]
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"]
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"]
    ElCol: typeof import("element-plus/es")["ElCol"]
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"]
    ElDialog: typeof import("element-plus/es")["ElDialog"]
    ElDivider: typeof import("element-plus/es")["ElDivider"]
    ElDropdown: typeof import("element-plus/es")["ElDropdown"]
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"]
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"]
    ElForm: typeof import("element-plus/es")["ElForm"]
    ElFormItem: typeof import("element-plus/es")["ElFormItem"]
    ElIcon: typeof import("element-plus/es")["ElIcon"]
    ElImageViewer: typeof import("element-plus/es")["ElImageViewer"]
    ElInput: typeof import("element-plus/es")["ElInput"]
    ElLink: typeof import("element-plus/es")["ElLink"]
    ElOption: typeof import("element-plus/es")["ElOption"]
    ElPagination: typeof import("element-plus/es")["ElPagination"]
    ElPopover: typeof import("element-plus/es")["ElPopover"]
    ElRow: typeof import("element-plus/es")["ElRow"]
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"]
    ElSelect: typeof import("element-plus/es")["ElSelect"]
    ElSwitch: typeof import("element-plus/es")["ElSwitch"]
    ElTabPane: typeof import("element-plus/es")["ElTabPane"]
    ElTabs: typeof import("element-plus/es")["ElTabs"]
    ElUpload: typeof import("element-plus/es")["ElUpload"]
    RouterLink: typeof import("vue-router")["RouterLink"]
    RouterView: typeof import("vue-router")["RouterView"]
    Screenfull: typeof import("./../components/Screenfull/index.vue")["default"]
    SvgIcon: typeof import("./../components/SvgIcon/index.vue")["default"]
    ThemeSwitch: typeof import("./../components/ThemeSwitch/index.vue")["default"]
    WarningBar: typeof import("./../components/WarningBar/warningBar.vue")["default"]
    DatePicker: typeof import("./../components/DatePicker/index.vue")["default"]
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import("element-plus/es")["ElLoadingDirective"]
  }
}
