captcha:
  img-height: 80
  img-width: 240
  key-long: 6
cors:
  mode: whitelist
  whitelist:
    - allow-credentials: true
      allow-headers: content-type
      allow-methods: GET, POST
      allow-origin: example1.com
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
    - allow-credentials: true
      allow-headers: content-type
      allow-methods: GET, POST
      allow-origin: example2.com
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
jwt:
  buffer-time: 43200
  expires-time: 86400
  issuer: pddZl
  signing-key: pddzl

# zap logger configuration
zap:
  level: info
  format: console
  prefix: ''
  director: /data/drawer/server.log
  show-line: true
  encode-level: CapitalColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

mysql:
  config: charset=utf8&parseTime=true&loc=Asia%2FShanghai
  db-name: init_drawer
  host: 127.0.0.1
  log-mode: false
  log-zap: true
  max-idle-conns: 10
  max-open-conns: 100
  password: 123.com
  port: 3306
  username: root
redis:
  db: 0
  host: redis
  password: ""
  port: 6379
rotatelogs:
  compress: true
  max-age: 90
  max-backups: 90
  max-size: 10
# system configuration
system:
  env: 'production' # Change to "develop" to skip authentication for development mode
  host: '0.0.0.0'
  port: '5558'
  stack: true
  use-multipoint: false

# 创建license的接口
license:
  url: "http://127.0.0.1:8100/app/tctest"
  auth: true
  authorization: "Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx="

# SMTP信息
smtp:
  user: "xxxx@xxxxx.com"
  password: "xxxxxx"
  server: "smtp.xxxxxx.outlook.cn"
  port: 587
  Starttls: true
